project1/project1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^stuff/', include('stuff.urls')),
    url(r'^admin/', admin.site.urls),
]

project1/stuff/urls.py
from django.conf.urls import url
from .views import IndexView, AnyPageView


app_name = 'stuff'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', AnyPageView.as_view(), name='list'),
]

project1/stuff/models.py
from django.db import models


class Page(models.Model):
    title = models.CharField(max_length=100)
    page_text = models.CharField(max_length=1000)
    created_by = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True)
    creation_date = models.DateTimeField('creation_date')
    image = models.ImageField(upload_to='images', null=True, blank=True)
    string = "images"

    def __str__(self):
        return self.title

    def has_image(self):
        return True if str(self.image).find(self.string) == 0 else False

    has_image.boolean = True

project1/stuff/views.py
from django.views.generic import ListView, DetailView

from .models import Page


class IndexView(ListView):
    template_name = 'stuff/pages_list.html'
    model = Page
    context_object_name = "objects"


class AnyPageView(DetailView):
    template_name = 'stuff/page.html'
    model = Page

project1/stuff/templates/stuff/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous" />
        <link rel="stylesheet" href="/home/ivan/mycode/project1/stuff/static/CSS/stylesheet.css" />
    </head>
    <body>
        <div id="content">
            {%block content%}
            {%endblock%}
        </div>
    </body>
</html>

project1/stuff/templates/stuff/page.html
{%extends 'stuff/base.html'%}
{%load static%}
{%block content%}
    <title>{{object.title}}</title>
    <section id="header" class="navbar nav-transparent text-primary">
        <div class="container">
            <div class="col-3">
            </div>
            <div class="col-1">
                <img src="http://dlyapun.com/static/images/django.png" height="50" width="50" />
            </div>
            <div class="col-8">
                <h1>Welcome to Django</h1>
            </div>
        </div>
    </section>
    <section id="main_section_page">
        <div class="container">
            <div class="row">
                <div class="col-3">
                    <div class="fill-viewport align-items-center">
                        <h2 class="lead text-info">Go back to our Main Page:</h2>
                        <h4><a href="{% url 'stuff:index' %}">Back to Pages</a></h4>
                    </div>
                </div>
                <div class="col-7">
                    <h2>Query title: {{object.title}}</h2>
                    <h4 id="text">Query text: </h4>
                    <p>{{object.page_text}}</p>
                    {% if object.image %}
                        <h4>Query image:</h4>
                        <img src="{{object.image.url}}" width="500" height="350" alt="Image not found" />
                    {% endif %}
                </div>
                <div class="col-2">
                    <h2 class="lead text-info">Query Info:</h2>
                    <h4>ID: {{object.id}}   </h4>
                    <h4>Creator: {{object.created_by}}</h4>
                    <h4>Creation date: {{object.creation_date}}</h4>
                </div>
            </div>
        </div>
    </section>
{%endblock%}

project1/stuff/templates/stuff/pages_list.html
{%extends 'stuff/base.html'%}
{%load static%}
{%block content%}
    <title>Pages list</title>
    <section id="header" class="navbar nav-transparent text-primary">
        <div class="container">
            <div class="col-3">
            </div>
            <div class="col-1">
                <img src="http://dlyapun.com/static/images/django.png" height="50" width="50" />
            </div>
            <div class="col-8">
                <h1>Welcome to Django</h1>
            </div>
        </div>
    </section>
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h6 class="text-uppercase text-black-40">about django...</h6>
                </div>
            </div>
        </div>
    </section>
    <section id="main_section_list">
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <div class="fill-viewport align-items-center">
                        <h2 class="lead text-info">Our Django Queries:</h2>
                        {%if objects%}
                            {%for element in objects%}
                                <ul class="list-unstyled">
                                    <li><a href="{%url 'stuff:list' element.id%}">{{element}}</a></li>
                                </ul>
                            {%endfor%}
                        {%else%}
                            <p>There are no pages in here...</p>
                        {%endif%}
                    </div>
                </div>
                <div class="col-8">
                    <h2 class="lead text-info">What is Django?</h2>
                    <p>Django is a free and open-source web framework, written in Python, which follows the model-view-template (MVT) architectural pattern.</p>
                    <p>Original Author: Lawrence Journal-World</p>
                    <p>Developers: Django Software Foundation</p>
                    <p>Initial release: 21 July 2005; 12 years ago</p>
                    <h3 class="lead text-info" id="more">More about Django:</h3>
                    <p id="sites"><a href="www.djangoproject.com">Website</a> and <a href="https://github.com/django/django">GitHub</a></p>
                </div>
            </div>
        </div>
    </section>
{%endblock%}